### PR TITLE
Lib tflite modifications

### PR DESCRIPTION
**Pull request by slahiruk**
Lib tflite modifications to support --> https://github.com/ctuning/ck-tensorflow/issues/138

### CODE REVIEW

**Comment by slahiruk** [comment]
https://github.com/slahiruk/ck-tensorflow/issues/1 Issue related to this pull request

**Comment by slahiruk** [comment]
Everything is working fine with this branch.

**Comment by psyhtest** [comment]
@slahiruk Thanks for your contribution. It's great it's all working! Please update the README and remove any Android patches - and the PR will be good to be merged.

**Comment by psyhtest** [comment]
@slahiruk Merged with thanks :)

**Comment by slahiruk** [comment]
@psyhtest Happy to work on this :)

**Pull request merged**
