### PR TITLE
FIX tf api compatibility problem

### PR DESCRIPTION
**Pull request by TITAN-PyCompat**
Dear developers,

I found some compatibility problems in your use of TensorFlow APIs, which might lead to crashes in a low version of TensorFlow. And I fix it for you as below:

`tf.global_variables_initializer` is the updated version of `tf.initialize_all_variables`, however, it appears until tf 0.12.0-rc0. So for version before that, it's better to use `tf.initialize_all_variables` to be safe.

@dsavenko @fanranGit @raduetsya @ens-lg4 @psyhtest 
Hope you could take my advice and look forward to your reply! 😄

### CODE REVIEW

**Comment by psyhtest** [comment]
Hi @TITAN-PyCompat, thanks for your contribution!
May I suggest to rewrite the Boolean expression:
```
if(tf.__version__.startswith("0.") and int(tf.__version__.split(".")[1])<12):
```
as:
```
tf_ver = [ int(x) for x in tf.__version__.split('.') ]
if(tf_ver[0] < 1 and tf_ver[1] < 12):
```

**Comment by TITAN-PyCompat** [comment]
@psyhtest Thanks for your reply! Of course ok! 👍

**Comment by TITAN-PyCompat** [comment]
Hi @psyhtest, thank you for you reply.
```python
tf_ver = [ int(x) for x in tf.__version__.split('.') ]
```
This may crash if alphabets like `rc` in `tf.__version__`, instead, I changed the condition into 
```python
tf_major_ver = int(tf.__version__.split(".")[0])
tf_minor_ver = int(tf.__version__.split(".")[1])
if(tf_major_ver == 0 and tf_minor_ver < 12):
```
Hope this can help.

**Comment by psyhtest** [comment]
LGTM!

Many thanks for your contribution... and until next time :)

**Pull request merged**
